NP fix issues
PMEAL/OpenPNM pull request #1585
Opened 2020-07-17 13:55 UTC by magnaou

- Fix reported issues related to PNP algs.
- Improve algs (performance, documentation, etc).

2020-07-18 05:06 UTC, ma-sadeghi reviewed
Looks good. One thing though, isn't the class name too long?

2020-07-18 14:38 UTC, ma-sadeghi requested changes
Can you please add unit tests for TransientIonicConduction's setup method as well as NernstPlanckMultiphysicsSolver? (both setup and run) Thanks!

2020-07-20 21:46 UTC, magnaou commented
yep, added.

2020-08-11 15:48 UTC, jgostick approved these changes

2020-08-11 15:48 UTC, ma-sadeghi approved these changes

2020-08-11 15:50 UTC, merged