Fix spacing issue for a network of two pores
PMEAL/OpenPNM pull request #1844
Opened 2021-02-11 15:54 UTC by Ni2M

This PR closes #1732 

Sample code:

import openpnm as op
import numpy as np
net = op.network.Cubic([1, 3, 1])
print(net.spacing)

output: 
[0. 1. 0.]

2021-02-12 14:39 UTC, ma-sadeghi requested changes
Great, could you also add a unit test to catch the corner cases? (the line with `raise Exception`, and the lines after `else` clause.

Also, could you try it with networks with only two pores? In your example, you have 3 pores. Try shape = [1, 2, 1] or [2, 1, 1]

2021-02-12 14:48 UTC, Ni2M commented
Thank you Amin for review and comments. For sure. I will implement them.

2021-02-12 15:49 UTC, Ni2M commented
After reviewing the code, I think we have two raise exception that are related. To raise an error in the first exception the throat must not be aligned with the lattice (directional throat) which can happen by changing the pore coords "test_spacing_on_joggled_network". This exception also occurs when we add boundary pores (which results in len(c.keys()) >sum(dims)) unit test of "test_spacing_on_network_with_boundary_pores". Both of these cases fall in the category of raise error later in the code ("A unique value of spacing could not be found"), but they are already captured ealier in with the first exception. If we try following code, they will be captured:
``` python
import openpnm as op
import numpy as np
from openpnm import topotools
net = op.network.Cubic([2, 2, 1])
#net.add_boundary_pores()
print(net['pore.coords'])
P12 = net["throat.conns"]
net['pore.coords'][2]=[1.2,0.5,0.5]# instead of [1.5,0.5,0.5]
C12 = net["pore.coords"][P12]
mag = np.linalg.norm(np.diff(C12, axis=1), axis=2)
unit_vec = np.around(np.squeeze(np.diff(C12, axis=1)) / mag, decimals=14)
spacing = [0, 0, 0]
dims = topotools.dimensionality(net)
# Ensure vectors point in n-dims unique directions
# c = {tuple(row): 1 for row in unit_vec}
# if len(c.keys()) >sum(dims):
#     raise Exception(
#         "Spacing is undefined when throats point in "
#         + "more directions than network has dimensions"
#     )
mag = np.float64(mag.squeeze())
for ax in [0, 1, 2]:
    if dims[ax]:
        inds = np.where(unit_vec[:, ax] == unit_vec[:, ax].max())[0]
        if np.ndim(mag) != 0:
            temp = np.unique(mag[inds])
            if not np.allclose(temp, temp[0]):
                raise Exception("A unique value of spacing could not be found")
            spacing[ax] = temp[0]
        else:
            temp = mag
            spacing[ax] = temp
print(spacing)
```

In other words, I could not find any other case that does not raise error in the first exception but still raises error in the second exception.

2021-02-12 15:54 UTC, Ni2M commented
Current results to check 2 pores:
```python
import openpnm as op
import numpy as np
#net = op.network.Cubic([1, 2, 1])
net = op.network.Cubic([2, 1, 1])
print(net.spacing)

#[0. 1. 0.]
#[1. 0. 0.]
```

2021-02-13 22:06 UTC, ma-sadeghi approved these changes

2021-02-13 22:09 UTC, merged